GET http://localhost:3000/bank-accounts

@id = 27a3389a-20a0-4361-9b07-dc094ce8aafa

###

GET http://localhost:3000/bank-accounts/{{id}}

###

POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-1",
  "owner_name": "John Doe"
}

###

GET http://localhost:3000/bank-accounts/{{id}}/pix-keys

###

POST http://localhost:3000/bank-accounts/{{id}}/pix-keys
Content-Type: application/json

{
  "kind": "email",
  "key": "user@email.com"
}
